
# some useful console commands

edit:
	emacs *.m makefile *.txt &

edit2:
	emacs *.m makefile *.txt

# need matlab 2011a to run endres code
# actually made a shortcut - just say
# > matlab2011a

matlab: 
	/lusr/share/software/matlab-2011a/bin/matlab &

# see who's using matlab
matstat:
	/v/filer4b/software/matlab-2011a/etc/lmstat -a

zip:
	zip -r motion2.zip readme.txt *.m scoresAll.mat paper
